# Generated by Django 2.2.6 on 2019-10-10 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('evaluate', models.FloatField(null=True)),
                ('station', models.CharField(blank=True, max_length=30)),
                ('genre', models.CharField(blank=True, max_length=30)),
                ('kuchikomi', models.IntegerField(null=True)),
                ('teikyu', models.CharField(blank=True, max_length=20)),
                ('lunch_bud', models.CharField(blank=True, max_length=20)),
                ('dinner_bud', models.CharField(blank=True, max_length=20)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('coordinate', models.CharField(blank=True, max_length=30)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.State')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
